### ISSUE TITLE
Conditional Operator is resulting in Wrong Value

### ISSUE THREAD

**Issue by vineet2garg** [IBM/JSONata4Java#26] opened 2020-02-26 01:16 UTC
Hi,
I am trying to parse a value using the conditional operator and it's resulting in incorrect value

jsonata string:
records.(

    $minLoadChargeCode := function($x) {(
		($x.CMD_Pricing_Plant_Code__c = 'WMC' and $x.APTS_Area__c = 'CON - WA MET' and $x.APTS_Minimum_Load_Fee__c = 45.0 ) ? 'WML' :
	    ($x.CMD_Pricing_Plant_Code__c = 'WMC' and $x.APTS_Area__c = 'CON - WA CTY' and $x.APTS_Minimum_Load_Fee__c = 75.0 ) ? 'WML' :
	    ($x.CMD_Pricing_Plant_Code__c = 'WMC' and $x.APTS_Area__c = 'CON - WA CTY' and $x.APTS_Minimum_Load_Fee__c != 75.0 ) ? 'WMO' :
	    ($x.CMD_Pricing_Plant_Code__c = 'WMC' and $x.APTS_Area__c = 'CON - WA MET' and $x.APTS_Minimum_Load_Fee__c != 45.0 ) ? 'WMO' :
	        $x.CMD_Minimum_Load_Charge_Code__c
	)};
	
	
{
    'CMD - Minimum Load Charge Code': $minLoadChargeCode(Apttus_Proposal__Proposal__r),
    'CMD_Pricing_Plant_Code__c' : Apttus_Proposal__Proposal__r.CMD_Pricing_Plant_Code__c,
    'APTS_Area__c' : Apttus_Proposal__Proposal__r.APTS_Area__c,
    'APTS_Minimum_Load_Fee__c' : Apttus_Proposal__Proposal__r.APTS_Minimum_Load_Fee__c,
    'CMD_Minimum_Load_Charge_Code__c' : Apttus_Proposal__Proposal__r.CMD_Minimum_Load_Charge_Code__c
})

---
The above function is returning the wrong evaluated value. Its always returning the last condition value.

The same parsing string work good on https://try.jsonata.org/ 

Please let me know if I am making any error.

**Comment by wnm3** [comment] 2020-03-02 14:16
I was away on vacation last week. I'll take a look to see if I can reproduce and fix if needed. Thanks for the submission.

**Comment by wnm3** [comment] 2020-03-02 14:30
I think I'm missing some of the data to provide a complete test case. Are you able to set this up in try.jsonata.org so I can see it working? There is likely a data structure that wasn't provided with the values of the various codes being tested in the function that is not part of this issue.

For example, where would I find the value for Apttus_Proposal__Proposal__r

**Comment by vineet2garg** [comment] 2020-03-02 23:13
Hi Nathaniel,

Thanks for reaching out.

Please find the sample JSON data and the jsonata script which I am using. This works on the https://try.jsonata.org/, but when I am using with the JSONata4Java library, its not evaluating the boolean conditions.



[sample.zip](https://github.com/IBM/JSONata4Java/files/4278398/sample.zip)

**Comment by wnm3** [comment] 2020-03-03 14:59
Perfect, thank you. I put this into the try.jsonata.org site here: https://try.jsonata.org/o2QqIWGy

I assume this is the expected output:
{
  "Quote/Proposal: Proposal ID": "Q-00030709",
  "Customer Number": "746272",
  "Customer Name": "ROBUST CONTRACTING",
  "Sales Rep Id": "999",
  "CMD - Pricing Plant Code": "WMC",
  "CMD - Minimum Load Charge Code": "WMO",
  "CMD - Customer Segment": "CO",
  "Price Category": "W13",
  "CMD  - Surcharge Code": "QXD",
  "CMD - Extra Cartage": 2.5,
  "CMD - Default Action": "Default to order if no project",
  "Admin Discount2": 6.9767,
  "CMD - Sundry Charge Code (OOH Weekday)": "W04",
  "CMD - Sundry Fee (OOH Weekday)": "",
  "CMD - Sundry Charge Code (OOH Saturday)": "W07",
  "CMD - Sundry Fee (OOH Saturday)": 60,
  "CMD - Sundry Charge Code (OOH Sunday)": "W09",
  "CMD - Sundry Fee (OOH Sunday)": "",
  "CMD - Sundry Price Extension": null,
  "CMD - Sundry Fee (Effective Date)": "2020-03-03T14:55:27.659Z",
  "CMD - Zone": null,
  "Owner Email": "pearl.lee@boral.com.au",
  "Area": "CON - WA CTY",
  "ProcessingUnit": "MuleSoft"
}

**Comment by wnm3** [comment] 2020-03-03 15:07
Using the Tester, the results differ as highlighted below:
{
  "Quote/Proposal: Proposal ID" : "Q-00030709",
  "Customer Number" : "746272",
  "Customer Name" : "ROBUST CONTRACTING",
  "Sales Rep Id" : "999",
  "CMD - Pricing Plant Code" : "WMC",
  "CMD - Minimum Load Charge Code" : "WMO",
  "CMD - Customer Segment" : "CO",
  "Price Category" : "W13",
  "CMD  - Surcharge Code" : "QXD",
  "CMD - Extra Cartage" : 2.5,
  "CMD - Default Action" : **_"Default to order"_**,
  "Admin Discount2" : 6.9767,
  "CMD - Sundry Charge Code (OOH Weekday)" : "W04",
  "CMD - Sundry Fee (OOH Weekday)" : "",
  "CMD - Sundry Charge Code (OOH Saturday)" : "W07",
  "CMD - Sundry Fee (OOH Saturday)" : 60**_.0_**,
  "CMD - Sundry Charge Code (OOH Sunday)" : "W09",
  "CMD - Sundry Fee (OOH Sunday)" : "",
  "CMD - Sundry Price Extension" : null,
  "CMD - Sundry Fee (Effective Date)" : **_"2020-03-03T15:03:08.061Z"_**,
  "CMD - Zone" : null,
  "Owner Email" : "pearl.lee@boral.com.au",
  "Area" : "CON - WA CTY",
  "ProcessingUnit" : "MuleSoft"
}

**Comment by wnm3** [comment] 2020-03-03 15:21
Can reproduce the problem using this expression in the Tester with the records data:

( 	    (records.RecordType.Name = 'Customer Master' and records.CMD_Pricing_Plant_Code__c = 'WMC' and records.APTS_Area__c = 'CON - WA MET' and records.APTS_Extra_Cartage__c != 2.5) ? 	        'Default to order if no project' : 	    (records.RecordType.Name = 'Customer Master' and records.CMD_Pricing_Plant_Code__c ='WMC' and records.APTS_Area__c = 'CON - WA CTY' and records.APTS_Extra_Cartage__c != 3.0) ? 	        'Default to order if no project' : 	    (records.RecordType.Name = 'Project Quote' and records.CMD_Pricing_Plant_Code__c ='WMC' and records.APTS_Area__c = 'CON - WA CTY' and records.APTS_Extra_Cartage__c != 3.0) ? 	        'Default to order' :  	    (records.RecordType.Name = 'Project Quote' and records.CMD_Pricing_Plant_Code__c ='WMC' and records.APTS_Area__c = 'CON - WA MET' and records.APTS_Extra_Cartage__c != 2.5) ? 	        'Default to order' : CMD_Default_Action__c )

**Comment by wnm3** [comment] 2020-03-03 15:26
Or more simply:
( (true and false) ? "one" : (true and true) ? "two" : (false and true) ? "three" : (false and false) ? "four" : "five" )
which returns four rather than two...

**Comment by wnm3** [comment] 2020-03-03 16:08
I have pushed a fix. If you are able to pull to refresh your cloned workspace and execute the pom.xml using clean install you should be able to run Tester and using the expression below, get back "two":

( (true and false) ? "one" : (true and true) ? "two" : (false and true) ? "three" : (false and false) ? "four" : "five" )

Your test case works now but of course the effective date is the current time so that will differ from one run to the next.

I'll push an update to Maven Central with an updated version number but that will take a couple of hours.

**Comment by wnm3** [comment] 2020-03-03 16:21
Please close this issue if you believe the problem is resolved. Thank you.

**Comment by wnm3** [comment] 2020-03-03 16:22
Later today you should see version 1.2.1 in Maven Central here: 
https://search.maven.org/search?q=g:com.ibm.jsonata4java

**Comment by wnm3** [comment] 2020-03-03 18:36
The 1.2.1 jar is now available from maven at the URL above.

**Comment by vineet2garg** [comment] 2020-03-04 00:09
Thanks, Nathaniel,
I will update the pom.xml and will download the latest version and will test.

Thanks once again for the pick reply.

**Closed** 2020-03-04 00:09 UTC
