### ISSUE TITLE
Path Operators "%.%." error

### ISSUE THREAD

**Issue by jiesiro** [IBM/JSONata4Java#215] opened 2022-10-13 12:15 UTC
json:{
    "data":[
        {
          
            "name":"root-type:p",
            "xxa":[
                "module=2122"
            ],
            "xxb":[
                {
                   
                    "datavalue":[
                        {
                            "value":0.24,
                            "timestamp":1664339583
                        },
                        {
                            "value":0.25,
                            "timestamp":1664341325
                        }
                    ]
                }
            ]
        }
    ]
}
jsonata:

data.xxb.datavalue.{

    "properties": {"value":value},
    "timestamp":timestamp,
    "mId":%.%.xxa,
    "oId":%.%.name
    
    }

java error:

mismatched input '%' expecting {'(', ')', 'true', 'false', STRING, 'null', '[', '{', '$', '$$', '**', NUMBER, FUNCTIONID, '*', '/', '-', VAR_ID, ID}
, line 6:20 at [@31,151:151='.',<1>,6:20]: mismatched input '.' expecting {'(', 'true', 'false', STRING, 'null', '[', '{', '$', '$$', '**', NUMBER, FUNCTIONID, '*', '/', '-', VAR_ID, ID}
, line 6:21 at [@32,152:152='%',<34>,6:21]: mismatched input '%' expecting {'(', 'true', 'false', STRING, 'null', '[', '{', '$', '$$', '**', NUMBER, FUNCTIONID, '*', '/', '-', VAR_ID, ID}
, line 6:22 at [@33,153:153='.',<1>,6:22]: extraneous input '.' expecting {'(', 'true', 'false', STRING, 'null', '[', '{', '$', '$$', '**', NUMBER, FUNCTIONID, '*', '/', '-', VAR_ID, ID}
, line 6:30 at [@38,161:161=')',<7>,6:30]: mismatched input ')' expecting {'.', 'in', '?', '[', ']', '{', '~>', '*', '/', '+', '-', '%', '=', '!=', '<', '<=', '>', '>=', '&', 'and', 'or'}

**Comment by bluemel** [comment] 2022-10-13 20:45
Hi jiesiro, I wanted to have a short try with the json and jsonata shown above in the original JSONata exerciser... and failed.
The JSON is syntactically incorrect: did you mean this?

{
  "data": [
    {
      "name": "root-type:p",
      "xxa": [
        "module=2122"
      ],
      "xxb": [
        {
          "datavalue": [
            {
              "value": 0.24,
              "timestamp": 1664339583
            },
            {
              "value": 0.25,
              "timestamp": 1664341325
            }
          ]
        }
      ]
    }
  ]
}

**Comment by bluemel** [comment] 2022-10-13 20:51
But using this input if have problems to get a reasonable result in the original JSONata exerciser.
![exerciser](https://user-images.githubusercontent.com/1290583/195707951-d0d8730a-ee82-47e9-81dd-3cdb4913e793.png)

**Comment by bluemel** [comment] 2022-10-13 21:01
Ok I've seen my mistake... oversaw the first line of your mapping expression.
![exerciser](https://user-images.githubusercontent.com/1290583/195709736-ab206c34-d090-43b9-9e06-95a93ca620a5.png)
Now it works out.

**Comment by jiesiro** [comment] 2022-10-14 04:39
ok, in the future JSONata4Java will support "%."   Operator?   Or there is a substitute for “%.” ?   Grammar, please ask

**Comment by jiesiro** [comment] 2022-10-14 04:42
> ok, in the future JSONata4Java will support "%." Operator? Or there is a substitute for “%.” ? Grammar, please ask

ok, in the future JSONata4Java will support "%." Operator? Or there is a substitute for “%.” ? Grammar, please ask

**Comment by jiesiro** [comment] 2022-10-14 04:42
> Ok I've seen my mistake... oversaw the first line of your mapping expression. ![exerciser](https://user-images.githubusercontent.com/1290583/195709736-ab206c34-d090-43b9-9e06-95a93ca620a5.png) Now it works out.

ok, in the future JSONata4Java will support "%." Operator? Or there is a substitute for “%.” ? Grammar, please ask

**Comment by bluemel** [comment] 2022-10-14 09:11
Sorry jiesiro, I currently do not know any substitute or workaround for this mapping problem here. I personally think the Parent path operator is relatlively important feature and in my eyes the project should strive to support it, but I currently do not have enough insights to make any predictions if and when it will.

By the way I would recommend to close this issue here as a duplicate of https://github.com/IBM/JSONata4Java/issues/214

**Comment by jiesiro** [comment] 2022-10-14 09:34
> 对不起 jiesiro，我目前不知道这里映射问题的任何替代或解决方法。我个人认为 Parent 路径操作符是相对重要的功能，在我看来，项目应该努力支持它，但我目前没有足够的洞察力来预测它是否会以及何时会。
> 
> 顺便说一句，我建议在此处关闭此问题，作为[#214的副本](https://github.com/IBM/JSONata4Java/issues/214)

OK, thank you.

**Closed** 2022-10-14 09:35 UTC
