### ISSUE TITLE
Array parsing incorrectly returns null

### ISSUE THREAD

**Issue by Charleeboyle** [IBM/JSONata4Java#29] opened 2020-03-09 13:10 UTC
When attempting to parse an ArrayNode with value
```
[
    {
        "name": "one",
        "age": 1
    },
    {
        "name": "two",
        "age": 2
    },
    {
        "name": "three",
        "age": 3
    }
]
```

using expression `name`, we receive `null` from `Expressions.parse("name").evaluate(inputJson)`

When inputting the same JSON and expression into https://try.jsonata.org, we get the correct expected output of 

```
[
  "one",
  "two",
  "three"
]
```

This seems like incorrect behaviour for the java implementation, we are only able to get non-null output from `evaluate()` when passing through an ObjectNode

**Comment by wnm3** [comment] 2020-03-09 13:19
I'll look into this ASAP. Thanks for providing the test case. I suspect I'm not expecting the Array as input, only an Object...

**Comment by wnm3** [comment] 2020-03-09 13:48
I have pushed a fix and am releasing version 1.2.2 to Maven Central. It will take a few hours before it posts but you can clone the repository and build using mvn clean install to get an updated jar in the target directory.

Please close this issue if you agree the problem is resolved. Thank you.

**Comment by Charleeboyle** [comment] 2020-03-09 14:25
I will pull the latest version and close the issue afterwards.

Thank you :)

**Comment by JDUNNIN** [comment] 2020-03-20 16:38
Just wrote a unit test for this and it's passing :)

**Closed** 2020-03-30 02:50 UTC
