### ISSUE TITLE
Issue with $join not taking single value

### ISSUE THREAD

**Issue by ChauhanSandeep** [IBM/JSONata4Java#24] opened 2019-12-19 12:08 UTC
I am getting EvaluateRuntimeException on applying $join method when only one argument is passed instead of array, but try.jsonata shows single value as result.
[http://try.jsonata.org/B1GdDJYRB](http://try.jsonata.org/B1GdDJYRB)

This is the error message I am getting:
`
Caused by: com.api.jsonata4java.expressions.EvaluateRuntimeException: Argument 1 of function $join must be an array of string
	at com.api.jsonata4java.expressions.functions.JoinFunction.invoke(JoinFunction.java:86)
	at com.api.jsonata4java.expressions.ExpressionsVisitor.visitFunction_call(ExpressionsVisitor.java:1329)
	at com.api.jsonata4java.expressions.ExpressionsVisitor.visitFunction_call(ExpressionsVisitor.java:81)
	at com.api.jsonata4java.expressions.generated.MappingExpressionParser$Function_callContext.accept(MappingExpressionParser.java:287)
	at org.antlr.v4.runtime.tree.AbstractParseTreeVisitor.visit(AbstractParseTreeVisitor.java:18)
	at com.api.jsonata4java.expressions.ExpressionsVisitor.lambda$visitObject_constructor$2(ExpressionsVisitor.java:1705)
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1382)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:482)`

I tried to make single value as array of string manually but this also throws exception :
[http://try.jsonata.org/Sk4meeFAB](http://try.jsonata.org/Sk4meeFAB)

**Comment by wnm3** [comment] 2019-12-20 17:06
Will fix this ASAP

**Comment by wnm3** [comment] 2019-12-20 18:03
I've checked in the fix for this. You'll need to pull and build to create the jars. I'm going to try to address another issue before checking in a new version to maven.

**Comment by wnm3** [comment] 2019-12-20 19:20
I have initiated the release process for a new version 1.2 of JSONata4Java that includes the bug fix as well as time boxing to test expressions to avoid infinite loops or unresolved recursion. See issue #23.

I expect Maven Central to have the update later today.

**Comment by wnm3** [comment] 2019-12-20 19:21
To test, I created a new file named jointestdata.json that includes your data structure. You can run the Tester program passing jointestdata.json as a parameter, then use your expression:
[Account.Order].{"id" : $join([Product.ProductID.$string()], ', ')}

Please comment and close if you believe the problem is addressed. Thank you.

**Comment by wnm3** [comment] 2020-03-30 03:12
I'm sorry, I lost track of this bug. I've fixed in and released version 1.3.1 tonight with the fix included.

I added a JUnit test based on the json object I use (it only has the Order's not the additional Product that your test had):
[Account.Order].{"id" : $join(Product.ProductID, ', ')} returned [{"id":"858383, 858236"},{"id":"858383, 345664"}]
See https://try.jsonata.org/khUZqxdJq

**Closed by wnm3** 2020-03-30 03:12 UTC
